name: '522-group31'

channels:
    - conda-forge
    - defaults
dependencies:
  - python=3.11
  - pandera=0.20.4
  - jupyterlab=4.3.1
  - ipykernel=6.29.5
  - matplotlib=3.9.2
  - pandas=2.2.3 
  - nb_conda_kernels=2.5.1
  - scikit-learn=1.5.2
  - requests=2.32.3   
  - altair-all=5.4.1
  - vegafusion=1.6.9
  - scipy=1.14.1  
  - quarto=1.5.57
  - click=8.1.7
  - tabulate=0.9.0
  - pytest=8.3.4
