name: '522-group31'

channels:
    - conda-forge
    - defaults
dependencies:
  - python==3.12
  - ipykernel
  - matplotlib
  - pandas
  - nb_conda_kernels
  - scikit-learn>=1.5.1
  - requests
  - altair-all=5.4.*
  - scipy
  - pip>=24.2
  - pip:
      - nbformat
