name: '522-group31'

channels:
    - conda-forge
dependencies:
  - python==3.11
  - pandera=0.20.4
  - jupyterlab
  - ipykernel
  - matplotlib
  - pandas
  - nb_conda_kernels
  - scikit-learn>=1.5.1
  - requests
  - altair-all=5.4.*
  - vegafusion==1.6.9
  - scipy
  - pip>=24.2
  - pip:
      - nbformat
      - altair_ally>=0.1.1
